from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from cassandra.cqlengine.connection import register_connection, set_default_connection
import json
import pathlib
import os

from dotenv import load_dotenv
load_dotenv()

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below


# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below

BASE_DIR = pathlib.Path(__file__).parent
CLUSTER_BUNDLE = str(BASE_DIR / "ignored" / "secure-connect-fitted.zip")
TOKEN_JSON = str(BASE_DIR / "ignored" / "mihirrocks9999@gmail.com-token.json")

with open(TOKEN_JSON) as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]



def get_cluster():
   cloud_config= {
    'secure_connect_bundle': CLUSTER_BUNDLE
    }
   auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
   cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
   return cluster

def get_session():
    cluster = get_cluster()
    session = cluster.connect()
    register_connection(name=str(session), session=session)
    set_default_connection(str(session))
    return session

# session = get_session()
# row = session.execute("select release_version from system.local").one()
# if row:
#     print(row[0])
# else:
#     print("An error occurred.")